//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KutuphaneOtm.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emanetler
    {
        public int EmanetID { get; set; }
        public Nullable<int> UyeID { get; set; }
        public Nullable<int> KitapID { get; set; }
        public Nullable<System.DateTime> EmanetVerilmeTarih { get; set; }
        public Nullable<System.DateTime> EmanetGeriAlmaTarihi { get; set; }
        public string EmanetNot { get; set; }
    
        public virtual Kitaplar Kitaplar { get; set; }
        public virtual Uye Uye { get; set; }
    }
}
