//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KutuphaneOtm.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kitaplar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kitaplar()
        {
            this.Emanetler = new HashSet<Emanetler>();
        }
    
        public int KitapID { get; set; }
        public string KitapAd { get; set; }
        public string KitapTur { get; set; }
        public string KitapYayinEvi { get; set; }
        public Nullable<int> KitapSayfaSayısı { get; set; }
        public string KitapYazar { get; set; }
        public string KitapDil { get; set; }
        public string KitapAciklama { get; set; }
        public Nullable<int> KitapAdet { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Emanetler> Emanetler { get; set; }
    }
}
